class XEControllerLabPro{
constructor(){this.index=null;this.pad=null;this.last=0;this.hz=[];this.phase="sticks";this.finished=false;this.profile=null;this.started=performance.now();this.eventHistory=[];this.prevButtons={};this.data={ls:this.stickData(),rs:this.stickData(),lt:this.triggerData(),rt:this.triggerData(),buttons:{},findings:[],score:100};this.names=["A","B","X","Y","LB","RB","VIEW","MENU","LS","RS","UP","DOWN","LEFT","RIGHT","GUIDE"];this.manualIndex=null;this.padSignature="";this.buttonMap={A:0,B:1,X:2,Y:3,LB:4,RB:5,VIEW:8,MENU:9,LS:10,RS:11,UP:12,DOWN:13,LEFT:14,RIGHT:15,GUIDE:16};this.initButtons();this.bind();this.loop()}
stickData(){return{max:0,centerValue:0,centerSamples:[],bins:new Set(),centerFrames:0,samples:0,x:0,y:0,frozen:false,lastX:0,lastY:0,noiseSamples:[],noise:0,snapback:0,wasEdge:false,releaseFrames:0,lastAngle:null,angularTravel:0,turns:0}}
triggerData(){return{hits:0,armed:true,max:0,jitter:0,last:0}}
initButtons(){let g=document.getElementById("buttonGrid");this.names.forEach(n=>{this.data.buttons[n]=false;g.insertAdjacentHTML("beforeend",`<div class="buttonItem" id="bi-${n}"><span>${n}</span><b>○</b></div>`)})}
bind(){window.addEventListener("gamepadconnected",e=>this.consider(e.gamepad));window.addEventListener("gamepaddisconnected",e=>{if(e.gamepad.index===this.index)this.disconnect()});document.addEventListener("visibilitychange",()=>{if(!document.hidden)this.scan()});window.addEventListener("focus",()=>this.scan());document.getElementById("rawToggle").onclick=()=>document.getElementById("rawData").classList.toggle("hidden");document.getElementById("restart").onclick=()=>location.reload();document.getElementById("pdf").onclick=()=>this.pdf();document.getElementById("refreshPads").onclick=()=>this.refreshPadList(true);document.getElementById("gamepadSelect").onchange=e=>this.selectPad(e.target.value);["clientName","serial"].forEach(id=>document.getElementById(id).addEventListener("input",()=>this.renderReport()));this.refreshPadList(true)}
loop(t=0){this.scan();if(this.pad){let p=(navigator.getGamepads?.()||[])[this.index];if(p){this.pad=p;this.update(t,p)}}requestAnimationFrame(x=>this.loop(x))}
scan(){let pads=navigator.getGamepads?.()||[];this.refreshPadList();if(this.manualIndex!==null){let p=pads[this.manualIndex];if(p){if(this.index!==p.index)this.activatePad(p);return}}if(this.index!==null&&pads[this.index])return;for(let p of pads){if(p&&this.looksLikeController(p)&&this.hasInput(p)){this.consider(p);break}}}
looksLikeController(p){let id=(p.id||"").toLowerCase();if(/headset|headphone|audio|dac|speaker|microphone/.test(id))return false;return p.axes.length>=2&&p.buttons.length>=4}
refreshPadList(force=false){let pads=Array.from(navigator.getGamepads?.()||[]).filter(Boolean),sig=pads.map(p=>`${p.index}:${p.id}:${p.buttons.length}:${p.axes.length}`).join("|");if(!force&&sig===this.padSignature)return;this.padSignature=sig;let s=document.getElementById("gamepadSelect"),current=this.manualIndex===null?"":String(this.manualIndex);s.innerHTML='<option value="">AUTOMÁTICO · detectar mando por entrada</option>'+pads.map(p=>`<option value="${p.index}">${p.index} · ${this.escape(this.cleanName(p.id))} · ${p.buttons.length}B/${p.axes.length}A${this.looksLikeController(p)?"":" · POSIBLE NO MANDO"}</option>`).join("");s.value=current}
selectPad(v){if(v===""){this.manualIndex=null;this.index=null;this.pad=null;document.getElementById("status").textContent="Modo automático · presiona un botón del mando";return}this.manualIndex=Number(v);let p=(navigator.getGamepads?.()||[])[this.manualIndex];if(p)this.activatePad(p)}
activatePad(p){this.index=null;this.pad=null;this.consider(p)}
hasInput(p){return p.buttons.some(b=>b.pressed||b.value>.15)||p.axes.some(a=>Math.abs(a)>.25)}
consider(p){if(this.index!==null)return;this.index=p.index;this.pad=p;this.profile=this.resolveProfile(p);document.getElementById("connection").classList.replace("off","on");document.getElementById("status").textContent="Control conectado · diagnóstico en curso";document.getElementById("devName").textContent=this.profile.name;document.getElementById("devMap").textContent=p.mapping||"raw/no estándar";document.getElementById("devIO").textContent=`${p.buttons.length} / ${p.axes.length}`;document.getElementById("profile").textContent=this.profile.note;document.getElementById("mappingBadge").textContent=this.profile.label;document.getElementById("liveProfile").textContent=this.profile.label;let ds5=/dualsense|0ce6|0df2/i.test(p.id||"");document.getElementById("ds5Panel")?.classList.toggle("hidden",!ds5);if(ds5)window.XEDS5?.gamepadDetected(p)}
resolveProfile(p){let id=(p.id||"").toLowerCase();if(id.includes("elite")||id.includes("0b00")||id.includes("02e3"))return{name:"Xbox Elite Series 2",label:"ELITE S2",note:"Perfil Xbox Elite Series 2 · lectura normalizada Gamepad API",map:{...this.buttonMap},axes:[0,1,2,3],triggers:[6,7]};if(id.includes("xbox")||id.includes("xinput")||id.includes("045e"))return{name:"Control Xbox / XInput",label:"XBOX",note:"Perfil estándar Xbox / XInput",map:{...this.buttonMap},axes:[0,1,2,3],triggers:[6,7]};if(id.includes("dualsense")||id.includes("dualshock")||id.includes("playstation")||id.includes("054c"))return{name:"Control PlayStation",label:"PLAYSTATION",note:"Perfil estándar normalizado por navegador",map:{...this.buttonMap},axes:[0,1,2,3],triggers:[6,7]};return{name:this.cleanName(p.id),label:p.mapping==="standard"?"STANDARD":"RAW",note:p.mapping==="standard"?"Mapeo estándar del navegador":"Control no estándar: monitor RAW activo para verificación",map:{...this.buttonMap},axes:[0,1,2,3],triggers:[6,7]}}
cleanName(id){return(id||"Control genérico").replace(/\([^)]*\)/g,"").slice(0,70)}
disconnect(){this.index=null;this.pad=null;this.manualIndex=null;this.refreshPadList(true);document.getElementById("connection").classList.replace("on","off");document.getElementById("status").textContent="Control desconectado"}
update(t,p){let dt=t-this.last;if(dt>0&&this.last){this.hz.push(1000/dt);if(this.hz.length>60)this.hz.shift();document.getElementById("polling").textContent=Math.round(this.hz.reduce((a,b)=>a+b,0)/this.hz.length)+" Hz"}this.last=t;let ax=this.profile.axes.map(i=>p.axes[i]??0),lt=this.readTrigger(p,this.profile.triggers[0]),rt=this.readTrigger(p,this.profile.triggers[1]);this.live(ax,lt,rt,p);this.raw(p);this.captureButtonEdges(p);if(this.finished)return;if(this.phase==="sticks")this.testSticks(ax);else if(this.phase==="triggers")this.testTriggers(lt,rt);else if(this.phase==="buttons")this.testButtons(p)}
readTrigger(p,i){let b=p.buttons[i];return b?Math.max(0,Math.min(1,b.value??(b.pressed?1:0))):0}
live(a,lt,rt,p){document.getElementById("liveLS").textContent=`${a[0].toFixed(3)} / ${a[1].toFixed(3)}`;document.getElementById("liveRS").textContent=`${a[2].toFixed(3)} / ${a[3].toFixed(3)}`;document.getElementById("liveLT").textContent=lt.toFixed(3);document.getElementById("liveRT").textContent=rt.toFixed(3);for(let k of ["LT","RT"]){let v=k==="LT"?lt:rt;document.getElementById("visual"+k).style.width=v*100+"%";document.getElementById("visual"+k+"Pct").textContent=Math.round(v*100)+"%"}document.querySelector(".digitalTrigger.lt").classList.toggle("active",lt>.05);document.querySelector(".digitalTrigger.rt").classList.toggle("active",rt>.05);document.querySelector("#stickL i").style.transform=`translate(${a[0]*10}px,${a[1]*10}px)`;document.querySelector("#stickR i").style.transform=`translate(${a[2]*10}px,${a[3]*10}px)`;for(let [n,i] of Object.entries(this.profile.map)){let el=document.querySelector(`[data-v="${n}"]`);if(el)el.classList.toggle("pressed",!!p.buttons[i]?.pressed)}}
raw(p){document.getElementById("rawData").innerHTML=`ID: ${this.escape(p.id)}<br>mapping: ${p.mapping||"(vacío)"}<br>buttons(${p.buttons.length}): ${p.buttons.map((b,i)=>`${i}:${b.value.toFixed(3)}${b.pressed?"*":""}`).join(" | ")}<br>axes(${p.axes.length}): ${p.axes.map((a,i)=>`${i}:${a.toFixed(4)}`).join(" | ")}`}
captureButtonEdges(p){if(!this.profile)return;for(let [n,i] of Object.entries(this.profile.map)){let now=!!p.buttons[i]?.pressed,prev=!!this.prevButtons[n];if(now!==prev){this.eventHistory.push({time:(performance.now()-this.started)/1000,name:n,state:now?"DOWN":"UP"});if(this.eventHistory.length>40)this.eventHistory.shift();this.renderEvents()}this.prevButtons[n]=now}}
renderEvents(){let e=document.getElementById("eventLog");if(!this.eventHistory.length)return;e.innerHTML=this.eventHistory.slice(-12).reverse().map(x=>`<span><b>${x.time.toFixed(3)}s</b> ${x.name} ${x.state}</span>`).join("")}
testSticks(a){this.sampleStick("ls",a[0],a[1],"ls");this.sampleStick("rs",a[2],a[3],"rs");if(this.stickReady(this.data.ls)&&this.stickReady(this.data.rs))this.next("triggers")}
sampleStick(k,x,y,prefix){let d=this.data[k],dist=Math.hypot(x,y);if(d.frozen)return;if(dist>.65){let angleNow=Math.atan2(y,x);if(d.lastAngle!==null){let delta=angleNow-d.lastAngle;while(delta>Math.PI)delta-=Math.PI*2;while(delta<-Math.PI)delta+=Math.PI*2;if(Math.abs(delta)<.65)d.angularTravel+=Math.abs(delta)}d.lastAngle=angleNow;d.turns=Math.min(6,Math.floor(d.angularTravel/(Math.PI*2)))}else if(dist<.35){d.lastAngle=null;}d.x=x;d.y=y;d.samples++;d.max=Math.max(d.max,dist);if(dist>.65){let angle=(Math.atan2(y,x)+Math.PI*2)%(Math.PI*2);d.bins.add(Math.floor(angle/(Math.PI*2)*16));d.wasEdge=true;d.releaseFrames=0}else if(d.wasEdge){d.releaseFrames++;if(d.releaseFrames<=12)d.snapback=Math.max(d.snapback,dist);if(dist<.18&&d.releaseFrames>2)d.wasEdge=false}if(dist<.18){d.centerFrames++;d.centerSamples.push(dist);if(d.centerSamples.length>120)d.centerSamples.shift();let delta=Math.hypot(x-d.lastX,y-d.lastY);d.noiseSamples.push(delta);if(d.noiseSamples.length>120)d.noiseSamples.shift();d.noise=d.noiseSamples.reduce((a,b)=>a+b,0)/Math.max(1,d.noiseSamples.length);let sorted=[...d.centerSamples].sort((a,b)=>a-b),cut=Math.max(1,Math.floor(sorted.length*.8));d.centerValue=sorted.slice(0,cut).reduce((a,b)=>a+b,0)/cut}d.lastX=x;d.lastY=y;let stability=Math.max(0,100-(d.noise*900+d.centerValue*350));document.getElementById(prefix+"Drift").textContent=(d.centerValue*100).toFixed(2)+"%";document.getElementById(prefix+"Range").textContent=Math.min(100,d.max*100).toFixed(0)+"%";document.getElementById(prefix+"Coverage").textContent=Math.round(d.bins.size/16*100)+"%";let noiseEl=document.getElementById(prefix+"Noise");if(noiseEl)noiseEl.textContent=(d.noise*100).toFixed(2)+"%";document.getElementById(prefix+"Stability").textContent=stability.toFixed(0)+"%";let turnsEl=document.getElementById(prefix+"Turns");if(turnsEl)turnsEl.textContent=d.turns+" / 6";let snapEl=document.getElementById(prefix+"Snapback");if(snapEl)snapEl.textContent=(d.snapback*100).toFixed(2)+"%";this.draw(prefix,x,y,d.bins)}
stickReady(d){return d.turns>=6&&d.max>.82&&d.bins.size>=12&&d.centerFrames>=25&&d.centerSamples.length>=25}
draw(id,x,y,bins){let c=document.getElementById(id),q=c.getContext("2d"),cx=110,cy=110,r=94;q.clearRect(0,0,220,220);q.strokeStyle="rgba(212,175,55,.22)";q.lineWidth=1;q.beginPath();q.arc(cx,cy,r,0,Math.PI*2);q.stroke();q.beginPath();q.moveTo(cx,8);q.lineTo(cx,212);q.moveTo(8,cy);q.lineTo(212,cy);q.stroke();for(let b of bins){let an=(b+.5)/16*Math.PI*2;q.strokeStyle="rgba(244,213,119,.55)";q.beginPath();q.arc(cx,cy,r-4,an-.12,an+.12);q.stroke()}q.strokeStyle="#d4af37";q.beginPath();q.moveTo(cx,cy);q.lineTo(cx+x*r,cy+y*r);q.stroke();q.fillStyle="#f4d577";q.shadowBlur=15;q.shadowColor="#d4af37";q.beginPath();q.arc(cx+x*r,cy+y*r,7,0,Math.PI*2);q.fill();q.shadowBlur=0}
testTriggers(lt,rt){this.trigger("lt",lt);this.trigger("rt",rt);if(this.data.lt.hits>=3&&this.data.rt.hits>=3)this.next("buttons")}
trigger(k,v){let d=this.data[k];d.max=Math.max(d.max,v);if(Math.abs(v-d.last)>.08&&Math.abs(v-d.last)<.8)d.jitter++;if(d.armed&&v>.94){d.hits++;d.armed=false}if(v<.1)d.armed=true;d.last=v;document.getElementById(k+"Bar").style.width=v*100+"%";document.getElementById(k+"Pct").textContent=(v*100).toFixed(0)+"%";document.getElementById(k+"Hits").textContent=Math.min(d.hits,3)+" / 3 recorridos";document.getElementById(k+"Noise").textContent=d.jitter+" eventos"}
testButtons(p){for(let [n,i] of Object.entries(this.profile.map)){if(!Object.prototype.hasOwnProperty.call(this.data.buttons,n))continue;if(p.buttons[i]?.pressed){this.data.buttons[n]=true;let el=document.getElementById("bi-"+n);el.classList.add("hit");el.querySelector("b").textContent="✓"}}if(this.names.every(n=>this.data.buttons[n]))this.finish()}
next(phase){let completed=this.phase;this.freezeCompletedTest(completed);document.getElementById("test-"+completed).classList.remove("active");document.getElementById("test-"+completed).classList.add("complete");document.getElementById("state-"+completed).textContent="COMPLETADO ✓";document.querySelector(`[data-step="${completed}"]`).classList.add("done");this.phase=phase;document.getElementById("test-"+phase).classList.remove("locked");document.getElementById("test-"+phase).classList.add("active");document.getElementById("state-"+phase).textContent="EN PRUEBA";document.querySelector(`[data-step="${phase}"]`).classList.add("active");document.getElementById("test-"+phase).scrollIntoView({behavior:"smooth",block:"center"})}
freezeCompletedTest(test){if(test==="sticks"){for(let k of ["ls","rs"]){let d=this.data[k];d.frozen=true;d.x=0;d.y=0;this.draw(k,0,0,d.bins)}document.querySelector("#stickL i").style.transform="translate(0px,0px)";document.querySelector("#stickR i").style.transform="translate(0px,0px)"}if(test==="triggers"){for(let k of ["lt","rt"]){document.getElementById(k+"Bar").style.width="0%";document.getElementById(k+"Pct").textContent="0%";this.data[k].last=0}}}
finish(){document.querySelectorAll("[data-v]").forEach(el=>el.classList.remove("pressed"));document.getElementById("test-buttons").classList.add("complete");document.getElementById("state-buttons").textContent="COMPLETADO ✓";document.querySelector('[data-step="buttons"]').classList.add("done");this.finished=true;this.phase="result";this.calculate();document.querySelector('[data-step="result"]').classList.add("active");document.getElementById("result").classList.remove("hidden");this.renderReport();document.getElementById("result").scrollIntoView({behavior:"smooth",block:"center"})}
calculate(){let score=100,f=[];for(let [k,label] of [["ls","Joystick izquierdo"],["rs","Joystick derecho"]]){let d=this.data[k],dr=d.centerValue*100;if(dr>5){score-=Math.min(25,(dr-5)*2);f.push(["bad",`${label}: drift de centro ${dr.toFixed(2)}%.`])}else f.push(["",`${label}: centro dentro del rango XE (${dr.toFixed(2)}%).`]);if(d.max<.9){score-=8;f.push(["bad",`${label}: rango máximo limitado (${(d.max*100).toFixed(1)}%).`])}}
for(let k of ["lt","rt"]){let d=this.data[k];if(d.max<.94){score-=12;f.push(["bad",`${k.toUpperCase()}: pérdida de rango, máximo ${(d.max*100).toFixed(1)}%.`])}else f.push(["",`${k.toUpperCase()}: recorrido completo verificado.`]);if(d.jitter>35){score-=8;f.push(["bad",`${k.toUpperCase()}: variación elevada detectada (${d.jitter} eventos).`])}}
score=Math.max(0,Math.round(score));let cl=score>=90?"EXCELENTE":score>=80?"MUY BUENO":score>=70?"BUENO":score>=60?"REGULAR":score>=40?"MALO":"REQUIERE REPARACIÓN";this.data.score=score;this.data.classification=cl;this.data.findings=f;document.getElementById("score").textContent=score;document.getElementById("classification").textContent=cl;document.getElementById("summary").textContent=score>=80?"El control completó las pruebas. Revisa el detalle técnico medido.":"Se detectaron valores que justifican revisión técnica.";document.getElementById("findings").innerHTML=f.map(x=>`<div class="finding ${x[0]}">${x[1]}</div>`).join("")}
renderReport(){if(!this.finished)return;let name=document.getElementById("clientName").value||"No especificado",serial=document.getElementById("serial").value||"No especificado";document.getElementById("reportPreview").innerHTML=`<div class="reportHead"><span>XE CONTROLLER LAB PRO</span><b>${this.data.score}/100 · ${this.data.classification}</b></div><div class="reportGrid"><span>Cliente<b>${this.escape(name)}</b></span><span>Serie / folio<b>${this.escape(serial)}</b></span><span>Control<b>${this.escape(this.profile.name)}</b></span><span>Perfil<b>${this.profile.label}</b></span><span>LS drift / rango<b>${(this.data.ls.centerValue*100).toFixed(2)}% / ${(this.data.ls.max*100).toFixed(1)}%</b></span><span>RS drift / rango<b>${(this.data.rs.centerValue*100).toFixed(2)}% / ${(this.data.rs.max*100).toFixed(1)}%</b></span><span>LT máximo<b>${(this.data.lt.max*100).toFixed(1)}%</b></span><span>RT máximo<b>${(this.data.rt.max*100).toFixed(1)}%</b></span></div>`}
async pdf(){
let name=document.getElementById("clientName").value||"No especificado",serial=document.getElementById("serial").value||"No especificado";
if(!window.jspdf){window.print();return}let {jsPDF}=window.jspdf,doc=new jsPDF({unit:"mm",format:"a4"}),W=210;
const G=[183,139,36],D=[18,18,18],Y=[95,95,95],L=[218,218,214],OK=[38,132,82],BAD=[184,56,62],P=[249,249,247];
const t=(v,x,y,s=8,st="normal",c=D,al="left")=>{doc.setFont("helvetica",st);doc.setFontSize(s);doc.setTextColor(...c);doc.text(String(v),x,y,{align:al})};
const bx=(x,y,w,h,f=[255,255,255],c=L)=>{doc.setFillColor(...f);doc.setDrawColor(...c);doc.roundedRect(x,y,w,h,1.5,1.5,"FD")};
const ln=(x1,y1,x2,y2,c=L)=>{doc.setDrawColor(...c);doc.line(x1,y1,x2,y2)};
const pc=v=>Math.max(0,Math.min(100,v)),fit=(v,n)=>String(v).length>n?String(v).slice(0,n-1)+"…":String(v);
const bar=(lab,v,x,y,w=67)=>{t(lab,x,y,6.2,"bold",Y);bx(x,y+1.8,w,3.8,[236,236,233]);doc.setFillColor(...G);doc.roundedRect(x,y+1.8,w*pc(v)/100,3.8,.6,.6,"F");t(pc(v).toFixed(1)+"%",x+w+3,y+5,6.2,"bold")};
let folio=serial==="No especificado"?"XE-"+Date.now().toString().slice(-8):serial;
let lh=pc(100-this.data.ls.centerValue*500-Math.max(0,90-this.data.ls.max*100)),rh=pc(100-this.data.rs.centerValue*500-Math.max(0,90-this.data.rs.max*100));
doc.setFillColor(...D);doc.rect(0,0,W,30,"F");doc.setFillColor(...G);doc.rect(0,29,W,1,"F");
t("XE",14,13,19,"bold",G);t("CONTROLLER LAB PRO",34,13,14,"bold",[225,225,225]);t("PROFESSIONAL CONTROLLER DIAGNOSTIC REPORT",14,21,6.5,"bold",[155,155,155]);
t("XE SERVICIO ELECTRÓNICO",196,12,7,"bold",G,"right");t("CHILPANCINGO, GUERRERO",196,19,6,"normal",[160,160,160],"right");
t("REPORTE TÉCNICO DE DIAGNÓSTICO",14,40,11,"bold");t("FOLIO "+folio,196,40,7,"bold",G,"right");ln(14,44,196,44,[205,185,125]);
t("CLIENTE",14,50,6,"bold",Y);t(fit(name,32),14,55,8,"bold");t("CONTROL",75,50,6,"bold",Y);t(fit(this.profile.name,34),75,55,8,"bold");t("PERFIL",142,50,6,"bold",Y);t(fit(this.profile.label,20),142,55,8,"bold");
bx(14,62,182,31,P,[205,185,125]);t("XE SCORE",21,70,7,"bold",G);t(this.data.score+"/100",21,83,20,"bold");t(this.data.classification,62,75,15,"bold",this.data.score>=80?OK:BAD);
t(this.data.score>=80?"Protocolo XE completado. Consulte mediciones y hallazgos técnicos.":"Se detectaron parámetros que requieren revisión técnica.",62,83,7,"normal",Y);t(new Date().toLocaleString("es-MX"),189,88,6,"normal",Y,"right");
t("MEDICIONES PRINCIPALES",14,101,9,"bold");bx(14,106,88,43);bx(108,106,88,43);t("JOYSTICKS",20,114,7,"bold",G);bar("LS RANGO",this.data.ls.max*100,20,120,52);bar("RS RANGO",this.data.rs.max*100,20,132,52);
t("DRIFT LS "+(this.data.ls.centerValue*100).toFixed(2)+"%",20,144,6.5,"bold",Y);t("DRIFT RS "+(this.data.rs.centerValue*100).toFixed(2)+"%",61,144,6.5,"bold",Y);
t("GATILLOS",114,114,7,"bold",G);bar("LT MÁXIMO",this.data.lt.max*100,114,120,52);bar("RT MÁXIMO",this.data.rt.max*100,114,132,52);t("LT CICLOS "+this.data.lt.hits,114,144,6.5,"bold",Y);t("RT CICLOS "+this.data.rt.hits,156,144,6.5,"bold",Y);
t("GRÁFICA COMPARATIVA DE SALUD",14,158,9,"bold");bx(14,163,182,39,P);[["JOYSTICK LS",lh],["JOYSTICK RS",rh],["GATILLO LT",this.data.lt.max*100],["GATILLO RT",this.data.rt.max*100]].forEach((v,i)=>bar(v[0],v[1],21,170+i*8,132));
t("HALLAZGOS TÉCNICOS",14,210,9,"bold");let fy=216;this.data.findings.slice(0,6).forEach(x=>{let bad=x[0]==="bad";bx(14,fy,182,6.5,bad?[255,247,247]:[247,251,248],bad?[230,185,185]:[190,218,199]);doc.setFillColor(...(bad?BAD:OK));doc.circle(18,fy+3.25,1.1,"F");t(bad?"REVISAR":"APROBADO",22,fy+4.2,5.8,"bold",bad?BAD:OK);t(fit(x[1],86),46,fy+4.2,5.8);fy+=7.5});
ln(14,263,196,263,[205,185,125]);t("CONCLUSIÓN TÉCNICA",14,269,7,"bold",G);let c=this.data.score>=90?"Parámetros medidos dentro de comportamiento óptimo según el protocolo XE.":this.data.score>=80?"Funcionamiento general satisfactorio; considerar los hallazgos indicados.":"Valores fuera del criterio de aprobación XE. Se recomienda revisión técnica.";t(c,14,275,7);t("XE Servicio Electrónico",196,275,7,"bold",D,"right");
doc.setFillColor(...D);doc.rect(0,284,W,13,"F");t("XE CONTROLLER LAB PRO · REPORTE GENERADO DIGITALMENTE",14,291.5,6,"bold",[175,175,175]);t("1 / 1",196,291.5,6,"bold",G,"right");
doc.save(`XE-Controller-Lab-Pro-Reporte-${Date.now()}.pdf`)
}
escape(s){return String(s).replace(/[&<>]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[m]))}}
new XEControllerLabPro();
